project_name: "my-pipeline-project"

var:
  auth:
    username: donny
    password: 43lw9rj2
    host: localhost
    port: "22"
    remotePath: /home/donny/workspaces/ini_test

direct_access:
  pipeline_dir: "./pipelines"
  ssh_configs:
    - Host: ssh_connection_target
      HostName: =var.auth.host
      User: =var.auth.username
      Port: =var.auth.port
      _Password: =var.auth.password
      RemoteCommand: mkdir -p =var.auth.remotePath && cd =var.auth.remotePath && bash -l
      RequestTty: force
      ServerAliveCountMax: "2"
      ServerAliveInterval: "300"
      StrictHostKeyChecking: "no"
  ssh_commands:
    - access_name: Enter Server
      command: ssh -v ssh_connection_target
  executions:
    - name: "Example Pipeline"
      key: "example"
      pipeline: "example-pipeline.yaml"
      hosts: []
      var: "var"
      variables: {}
    - name: "Agent File Transfer Sample"
      key: "agent-transfer"
      pipeline: "agent-file-transfer-sample.yaml"
      jobs: ["sync-site-agent"]
      hosts: ["ssh_connection_target"]  # Use the SSH config host name
      var: "default"
      variables: {}
    - name: "Local file-transfer soft (test)"
      pipeline: "file-transfer-soft.yaml"
      key: "file-transfer-soft-local"
      jobs: ["file-transfer-soft-job"]
      hosts: []
  